# pod specs for AgeEncryption
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  # deps
  pod 'AWSS3'
  pod 'AgeEncryption', '1.0.6'
  pod 'Alamofire'
end

target 'PluginTests' do
  capacitor_pods
end
