name: Build & Publish

on:
  push:
    branches:
      - master
    # tags-ignore:
    #   - '**'
    # paths:
    #   - 'android'
    #   - 'ios'
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    name: Check
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - run: npm run verify

      - run: npm run prepublishOnly

  publish:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release): publish')"
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - name: Publish to NPM
        run: npm publish --access public
