name: CI

on:
  push:
    branches:
      - master
    # tags-ignore:
    #   - '**'
    # paths:
    #   - 'android'
    #   - 'ios'
  pull_request:

env:
  NODE_VERSION: '18'
  JAVA_VERSION: '17'

jobs:
  test:
    runs-on: macos-latest
    name: Check
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: npm install

      - run: npm run verify

      - run: npm run prepublishOnly

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: "startsWith(github.event.head_commit.message, 'chore(release): publish')"
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - name: Add NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish to NPM
        run: npm publish --access public
