name: Build & Publish

on:
  push:
    branches:
      - master
    # tags-ignore:
    #   - '**'
    # paths:
    #   - 'android'
    #   - 'ios'
  pull_request:

env:
  NODE_VERSION: '18'
  JAVA_VERSION: '11'

jobs:
  test:
    runs-on: macos-latest
    name: Check
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - run: npm run verify

      - run: npm run prepublishOnly

  publish:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release): publish')"
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - name: Publish to NPM
        run: npm publish --access public
